### ISSUE TITLE
无法安装shapely

### ISSUE THREAD

**Issue by aoru45** [DataFountainCode/huawei_code_share#2]
2019-03-15 23:49:36,490 - connectionpool.py[line:735] - INFO: Starting new HTTPS connection (1): obs.myhwclouds.com
[dls_logger] dls-pipe found
Collecting shapely
The repository located at http is not a trusted or secure host and is being ignored. If this repository is available via HTTPS it is recommended to use HTTPS instead, otherwise you may silence this warning and allow it anyways with '--trusted-host http'.
Could not find a version that satisfies the requirement shapely (from versions: )
No matching distribution found for shapely
Traceback (most recent call last):
File "EAST/multigpu_train.py", line 25, in <module>
import icdar
File "/home/work/user-job-dir/EAST/icdar.py", line 13, in <module>
from shapely.geometry import Polygon
ModuleNotFoundError: No module named 'shapely

报错是上面的报错，请问有解决的办法吗？

**Comment by aoru45** [comment]
copy到gpu机器中安装whl，现在好像没联网了。
